---
abstract: 'Snake game'
author:
  - 'Jeffrey T. Palmer <jtpalmer@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Snake
requires:
  Moo: 0
  MooX::Types::MooseLike::Base: 0
  SDL: 2.500
  SDL::Event: 0
  SDLx::App: 0
  Sub::Quote: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/jtpalmer/Games-Snake/issues
  homepage: https://github.com/jtpalmer/Games-Snake
  repository: https://github.com/jtpalmer/Games-Snake.git
version: 0.000001
